import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Upload, AudioLines } from 'lucide-react';
export default function Arrangement(){
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const [status,setStatus]=useState('Memeriksa backend…');const [configured,setConfigured]=useState(false);const [busy,setBusy]=useState(false);const [result,setResult]=useState<File|null>(null);const [download,setDownload]=useState('');const [consent,setConsent]=useState(false);const abort=useRef<AbortController|null>(null);const navigate=useNavigate();
 useEffect(()=>{fetch('/api/piano/status').then(r=>{if(!r.ok)throw Error();return r.json();}).then(s=>{setStatus(s.message);setConfigured(s.configured);}).catch(()=>setStatus('Backend tidak dapat dijangkau.'));return()=>abort.current?.abort();},[]);
 useEffect(()=>{if(!file){setPreview('');return;}const u=URL.createObjectURL(file);setPreview(u);return()=>URL.revokeObjectURL(u);},[file]);
 useEffect(()=>{if(!result){setDownload('');return;}const u=URL.createObjectURL(result);setDownload(u);return()=>URL.revokeObjectURL(u);},[result]);
 const process=async()=>{if(!file)return;setBusy(true);setResult(null);setStatus('Mengunggah audio dan menunggu backend…');abort.current=new AbortController();try{const response=await fetch('/api/piano/arrange',{method:'POST',headers:{'Content-Type':/\.wav$/i.test(file.name)?'audio/wav':'audio/mpeg'},body:file,signal:abort.current.signal});if(!response.ok){const error=await response.json();throw Error(error.message||'Pemrosesan gagal.');}const blob=await response.blob();const bytes=new Uint8Array(await blob.arrayBuffer());if(new TextDecoder().decode(bytes.slice(0,4))!=='MThd')throw Error('Backend tidak mengembalikan MIDI valid.');setResult(new File([blob],'piano-arrangement.mid',{type:'audio/midi'}));setStatus('MIDI diterima dari model. Buka studio untuk memilih track, mengedit, dan memainkan hasilnya.');}catch(e){setStatus(e instanceof Error&&e.name==='AbortError'?'Permintaan dibatalkan.':e instanceof Error?e.message:'Pemrosesan gagal.');}finally{setBusy(false);}};
 return <div className="min-h-screen bg-[#120e1d] p-5 text-purple-50"><main className="!max-w-3xl !mx-auto !p-4"><Link to="/" className="text-sm text-violet-300">← SPONMUSIC</Link><div className="mt-10 flex items-center gap-3"><AudioLines className="text-violet-400"/><h1>AI Piano Arrangement</h1></div><p className="my-4 text-sm text-purple-200">Audio → model eksternal → Piano MIDI → piano roll & falling notes.</p><section className="panel p-6 space-y-5"><div className="rounded-xl border border-amber-500/30 bg-amber-950/20 p-4 text-sm text-amber-200">{configured?'Endpoint model sudah dikonfigurasi. Kualitas hasil bergantung model yang dipasang.':'Fondasi siap. Model AI belum tersedia: aplikasi tidak membuat MIDI contoh atau berpura-pura melakukan transkripsi.'}</div><label className="block cursor-pointer rounded-2xl border border-dashed border-violet-500 p-8 text-center"><Upload className="mx-auto mb-3 text-violet-300"/><span>{file?.name||'Pilih audio MP3 / WAV'}</span><input disabled={busy} className="mt-4 block w-full text-xs" type="file" accept=".mp3,.wav,audio/mpeg,audio/wav" onChange={e=>{const f=e.target.files?.[0];setResult(null);if(!f)return;if(!/\.(mp3|wav)$/i.test(f.name)||f.size>20000000){setFile(null);setStatus('Pilih MP3/WAV maksimal 20 MB.');return;}setFile(f);}}/><small className="mt-3 block text-purple-300">Maksimal 20 MB · YouTube belum didukung</small></label>{preview&&<audio controls src={preview} className="w-full"/>}<label className="flex gap-2 text-xs text-purple-200"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Saya berhak memproses audio ini dan mengizinkan pengirimannya ke backend serta model yang dikonfigurasi.</label><div className="flex flex-wrap gap-3"><Button className="primary-button" disabled={!file||!consent||busy} onClick={process}>{busy?'Memproses…':configured?'Proses aransemen piano':'Upload & periksa kesiapan'}</Button>{busy&&<Button className="soft-button" onClick={()=>abort.current?.abort()}>Batalkan</Button>}</div><p role="status" className="text-sm text-purple-200">{status}</p>{result&&<div className="flex flex-wrap gap-3"><Button className="primary-button" onClick={()=>navigate('/studio?mode=midi',{state:{midiFile:result,aiResult:true}})}>Buka piano roll / falling notes</Button><a className="soft-button inline-flex items-center" href={download} download="piano-arrangement.mid">Unduh MIDI</a></div>}<p className="text-xs text-purple-300">Audio tidak disimpan oleh backend SPONMUSIC. Hasil tidak disimpan otomatis sebelum dibuka di studio. Model eksternal harus memiliki kebijakan penyimpanannya sendiri.</p></section></main></div>;
}
