import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
type Metrics={total:number;min:number|null;max:number|null;octaves:Record<string,number>;intervals9:number;intervals12:number;octaveSwitches:number;rests:number;restSeconds:number;averageInterval:number;onsetProxyNotes:number};
type Report={transcription:Metrics;melody:Metrics;findings:string[];warning:string;tracks:{name:string;notes:number}[]};
export default function AudioDiagnostic(){
 const [file,setFile]=useState<File|null>(null),[report,setReport]=useState<Report|null>(null),[status,setStatus]=useState('Pilih audio nyata. Maksimal 20 MB / 60 detik.'),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false);const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const run=async()=>{if(!file)return;const c=new AbortController();controller.current=c;setBusy(true);setReport(null);
 const json=async(url:string,options:RequestInit={})=>{const r=await fetch(url,{...options,signal:c.signal});let data;try{data=await r.json();}catch{throw Error(`Respons non-JSON HTTP ${r.status}`);}if(!r.ok)throw Error(data.message||`HTTP ${r.status}`);return data;};
 try{setStatus('Upload…');const job=await json('/api/piano/jobs/submit',{method:'POST',headers:{'Content-Type':/\.wav$/i.test(file.name)?'audio/wav':'audio/mpeg'},body:file});const deadline=Date.now()+1800000;
 while(Date.now()<deadline){const state=await json(`/api/piano/jobs/${job.job_id}`);setStatus(`${job.job_id}: ${state.status}`);if(state.status==='failed')throw Error(state.error||'Transcription failed');if(state.status==='completed'){setStatus('Analisis transcription dan arrangement…');setReport(await json(`/api/dev/audio-diagnostic/${job.job_id}`));setStatus('Analisis selesai');return;}await new Promise<void>((resolve,reject)=>{const cancel=()=>{clearTimeout(timer);reject(new DOMException('Cancelled','AbortError'));};const timer=setTimeout(()=>{c.signal.removeEventListener('abort',cancel);resolve();},3000);c.signal.addEventListener('abort',cancel,{once:true});if(c.signal.aborted)cancel();});}throw Error('Batas menunggu 30 menit.');
 }catch(e){setStatus(e instanceof Error?e.message:'Diagnostic gagal');}finally{setBusy(false);}};
 return <main className="!max-w-5xl space-y-5"><h1>Developer · Audio diagnostic</h1><p className="text-purple-200">Tidak mengubah algoritma. Menggunakan service Basic Pitch yang dikonfigurasi dan engine arrangement saat ini.</p><input type="file" accept=".mp3,.wav" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f&&/\.(mp3|wav)$/i.test(f.name)&&f.size<=20000000)setFile(f);else{setFile(null);setStatus('Gunakan MP3/WAV maksimal 20 MB');}}}/><label className="flex gap-2"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Saya berhak menggunakan audio ini dan mengizinkan dikirim ke backend/model.</label><div className="flex gap-3"><Button disabled={!file||!consent||busy} onClick={run}>Jalankan diagnostic</Button>{busy&&<Button onClick={()=>controller.current?.abort()}>Hentikan menunggu</Button>}</div><p role="status">{status}</p>{report&&<><p className="rounded-xl border border-amber-700 p-4 text-amber-200">{report.warning}</p><h2>Indikasi heuristik (bukan root cause terverifikasi)</h2><ul>{report.findings.map(f=><li key={f}>{f}</li>)}</ul><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th className="text-left p-3">Metrik</th><th>Transcription post-processing</th><th>Final melody</th></tr></thead><tbody>{(['total','min','max','onsetProxyNotes','intervals9','intervals12','octaveSwitches','rests','restSeconds','averageInterval'] as const).map(k=><tr key={k} className="border-b border-purple-900"><td className="p-3">{k}</td><td className="text-center">{report.transcription[k]?.toFixed(2)??'—'}</td><td className="text-center">{report.melody[k]?.toFixed(2)??'—'}</td></tr>)}</tbody></table></div><h2>Transcription: jumlah not per oktaf</h2><pre>{JSON.stringify(report.transcription.octaves,null,2)}</pre><h2>Track hasil arrangement</h2><pre>{JSON.stringify(report.tracks,null,2)}</pre></>}</main>;
}
