import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { MidiImport, selectedMidi } from '@/lib/import-midi';
import { Project } from '@/lib/music';
import { toast } from 'sonner';
export default function MidiTrackPicker({data,onClose,onImport}:{data:MidiImport;onClose:()=>void;onImport:(p:Project)=>void}) {
 const [ids,setIds]=useState<number[]>(data.tracks.filter(t=>t.piano).map(t=>t.id));
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="studio-dialog"><DialogHeader><DialogTitle>Pilih track MIDI</DialogTitle></DialogHeader><p className="text-xs text-purple-200">{data.name} · Konversi +1 oktaf dari MIDI asli. Hanya track terpilih yang masuk piano roll dan falling notes.</p><div className="flex gap-2"><Button className="soft-button" onClick={()=>setIds(data.tracks.filter(t=>t.piano).map(t=>t.id))}>Piano saja</Button><Button className="soft-button" onClick={()=>setIds(data.tracks.map(t=>t.id))}>Semua</Button><Button className="soft-button" onClick={()=>setIds([])}>Kosongkan</Button></div><div className="max-h-72 overflow-auto space-y-2">{data.tracks.map(t=><label key={t.id} className="flex items-center gap-3 rounded-lg border border-purple-900 p-3 cursor-pointer"><input type="checkbox" checked={ids.includes(t.id)} onChange={e=>setIds(e.target.checked?[...ids,t.id]:ids.filter(id=>id!==t.id))}/><span className="text-sm">{t.name}<small className="block text-purple-300">{t.instrument} · {t.notes.length} not {t.piano?'· Piano':''}</small></span></label>)}</div><p className="text-xs text-purple-300">Deteksi piano memakai metadata instrumen MIDI. Jika piano dan bass sudah tercampur dalam satu track, pemilihan track tidak dapat memisahkannya. Semua track terpilih dimainkan dengan suara piano.</p><Button className="primary-button" disabled={!ids.length} onClick={()=>{try{onImport(selectedMidi(data,ids));}catch(e){toast.error(e instanceof Error?e.message:'Impor gagal');}}}>Impor {ids.length} track</Button></DialogContent></Dialog>;
}
